Fix free storace space calculation overflowing
rauc/rauc-hawkbit-updater pull request #50
Opened 2020-08-26 15:53 UTC by fshrOSB

The number of available bytes of storage calculated can overflow when there is too much free space.

On a machine where long is only 32 bits in size the overflow occurs with more than about 2 GB available.
The `get_available_space()` function then reports a negative value and the rollout fails with "Not enough free space" e.g..
`Error: Not enough free space. File size: 71264324. Free space: -94932992`

2020-08-26 20:15 UTC, ejoerns requested changes
@fshrOSB Thanks for your contribution! Please note that you can simply force-push to your PR branch to update the commit instead of closing and opening another one.

Otherwise, it looks like a reasonable fix and good catch. :+1: 

Please also add a proper prefix to the commit message (e.g. `src/hawkbit-client: ...`) and fix the minor typo ('storage').

2020-08-31 14:21 UTC, ejoerns reviewed
It basically looks ok for me (no idea why Travis is not responding here despite the build looks fine), theonly thing I came across when having a look at the corresponding code in RAUC is that we might want to use the `goffset` type here, too. Which is explicitly meant to be used for file sizes and offsets. Effectively it is the same as `gint64`.
Any opinions?

I also wondered whether glib has something built-in for getting free disk space. Having a short look into the manual shows there `is g_file_query_info()` and the `G_FILE_ATTRIBUTES`, but maybe this is a bit heavier than required.

2020-09-01 07:40 UTC, mschwan-phytec commented on src/hawkbit-client.c
> +
Please remove the added extra line at the end of the file. Everything else looks good to me.

2020-09-01 11:16 UTC, mschwan-phytec commented on src/hawkbit-client.c
> -
Thanks for fixing this. You should squash this commit into your previous one, as the newline was introduced by your previous commit of this PR.

2020-09-01 11:27 UTC, mschwan-phytec commented
Just a quick tip regarding you commit messages: You may want to keep the line width to a max. 72 characters. I don't think this is a strict requirement for this project but is good practice to increase readability.

2020-09-07 14:39 UTC, ejoerns commented
I'd really do this in a single commit (instead of moving form `long` -> `int64` -> `goffset`), but otherwise, it looks fine for me.

2020-09-07 14:53 UTC, fshrOSB commented
> It basically looks ok for me (no idea why Travis is not responding here despite the build looks fine), theonly thing I came across when having a look at the corresponding code in RAUC is that we might want to use the `goffset` type here, too. Which is explicitly meant to be used for file sizes and offsets. Effectively it is the same as `gint64`.
> Any opinions?
> 
> I also wondered whether glib has something built-in for getting free disk space. Having a short look into the manual shows there `is g_file_query_info()` and the `G_FILE_ATTRIBUTES`, but maybe this is a bit heavier than required.

I changed the type for the available space from `gint64` to `goffset`.

The `size` element of the `artifact` struct, to which the available space is compared to, should probably also switch to the `goffset` type in the future.
https://github.com/rauc/rauc-hawkbit-updater/blob/cb55819522be9566e074efd2d09d425a2f3ebc52/include/hawkbit-client.h#L73-L84

2020-09-09 07:01 UTC, ejoerns approved these changes
Thanks for your changes, looks fine for me now!

2020-09-09 07:05 UTC, merged